name: clearskies
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.7.0
  http: ^0.13.0
  args: ^2.0.0
  dart_console: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
